#!/usr/bin/env python3
import os
import select
import signal
import subprocess
import sys
import time


TARGETS = [
    "exceptions: self-test",
    "timer: monotonic self-test passed",
    "smp: per-core registry self-test passed",
    "VMM map/unmap self-test passed",
    "VMM MMIO device mappings installed",
    "arena: self-test passed",
    "sandbox: lifecycle self-test passed",
    "\"sandbox_transitions\":4",
    "source-index: fixture loaded files=2 symbols=2 updates=1",
    "git-workspace: self-test passed",
    "virtio-blk: read/write/error/reset self-test passed",
    "persistence: mutable state region sector=1536 sectors=1",
    "persistence: disk write sector=1536 version=1 records=5",
    "persistence: disk loaded sector=1536 version=1 records=5",
    "persistence: disk reload/rollback self-test passed snapshots=5 rollbacks=5 rejects=2 disk_writes=1 disk_loads=1 checksum_errors=0",
    "mutable-fs: mounted start=1600 metadata=16 journal=2 data=1618 sectors=96 nodes=32 policy=rw",
    "mutable-fs: write path=/state/services/source-index.state",
    "mutable-fs: snapshot committed",
    "mutable-fs: snapshot rollback",
    "mutable-fs: allocator self-test passed",
    "mutable-fs: directory tree self-test passed directories=11",
    "mutable-fs: multi-sector file self-test passed files=7 multi_sector=1",
    "mutable-fs: journal replay self-test passed replays=1 journal_writes=1",
    "mutable-fs: public API self-test passed list=1 stat=3 rename=1 open=3 close=3",
    "mutable-fs: subsystem records self-test passed records=4",
    "mutable-fs: self-test passed files=7 directories=11 writes=12 reads=6 deletes=1 commits=1 rollbacks=1 replays=1 rejects=8 checksum_errors=0",
    "update: self-test passed transactions=2 staged=2 committed=1 failed=1 recovered=1 rollbacks=1 boot_fallbacks=1 records=8 rollback_points=2 rejects=2",
    "core-lease: isolation self-test passed",
    "virtio-net: malformed packet/drop self-test passed",
    "virtio-net: rx/tx/reset self-test passed",
    "network: stack initialized",
    "network: udp flow id=",
    "expired queue=",
    "retransmit=1",
    "timeout queue=",
    "network: queue-backed udp/tcp self-test passed rx=6 tx=6 drops=2 lifecycle=18 udp_flows=1 udp_hits=1 udp_expired=1 tcp_timeouts=1 tcp_retransmits=1 queue_rx=6 queue_tx=6 queue_done=6 backpressure=0 flow_mismatch=0",
    "initramfs: config service=/init mode=qemu-mvp",
    "initramfs: service-manager path=/bin/service-manager descriptor=/etc/services/source-index.svc",
    "initramfs: child service=/svc/source-index parent=/init restart=never",
    "initramfs: mounted rofs version=2 files=6",
    "initramfs: rofs metadata/config self-test passed",
    "syscall: table self-test passed entries=15",
    "user: process table initialized slots=8",
    "user: process lifecycle invalid/failed transition self-test passed",
    "scheduler: lifecycle self-test passed",
    "user: process pid=1 name=/init state=loaded",
    "security: self-test passed denied=13 capability_denials=3 fs_denials=1 workspace_denials=1 sandbox_denials=1 rollback_denials=1 update_policy_rejects=3 credential_rejects=2 signature_accepts=1 signature_rejects=3 admin_denials=2 update_authorizations=1 update_replay_rejects=1 key_accepts=1 key_rejects=1 sandbox_escape_rejects=1",
    "model-arena: shared read-only arena self-test passed",
    "core-lease: owner=0 mask=0x2 acquired",
    "nic-conflict-agent",
    "core-conflict-agent",
    "workspace-conflict-agent",
    "ai-cell: descriptor ABI self-test passed accepts=5 rejects=4",
    "ai-cell: resource contract self-test passed admissions=2 rejects=10 arena_pages=160 arena_bytes=655360 queue_binds=3 queue_releases=3 workspace_binds=2 workspace_releases=2 conflicts=3",
    "ai-cell: lifecycle self-test passed",
    "kheap: self-test passed",
    "VMM translation test passed",
    "gic: discovery self-test passed",
    "PMM 1024 page allocate/free test passed",
    "cpu-ai-runtime: model manifest loaded",
    "cpu-ai-runtime: model file loaded id=2 name=cpu-ai-mvp",
    "cpu-ai-runtime: model file path=/models/cpu-ai-mvp.osaimodel admitted arena=2",
    "cpu-ai-runtime: tokenizer/runtime boundary self-test passed tokenizer_calls=2 runtime_calls=2",
    "cpu-ai-runtime: multi-cell shared weights self-test passed loads=2 shared_binds=2 kv_writes=8",
    "cpu-ai-runtime: model load failure self-test passed failures=3 gpu_rejects=1",
    "cpu-ai-runtime: model file loader self-test passed file_loads=1 file_rejects=3",
    "admission_rejects=5 checksum_failures=1",
    "cpu-ai-runtime: tokenizer binding and CPU dispatch self-test passed tokenizer_binds=2 kernel_dispatches=2",
    "cpu-ai-runtime: deterministic decode fixture input=ABCD output=1B1F2327",
    "cpu-ai-runtime: self-test passed",
    "ai-cell: multi-cell shared model/private kv self-test passed",
    "\"arena_committed_pages\"",
    "\"git_workspace_active\"",
    "\"git_workspace_syncs\"",
    "\"git_workspace_applies\"",
    "\"git_workspace_reverts\"",
    "\"git_workspace_conflicts\"",
    "\"persistence_snapshots\":7",
    "\"persistence_rollbacks\":7",
    "\"persistence_rejects\":2",
    "\"persistence_disk_writes\":1",
    "\"persistence_disk_loads\":1",
    "\"persistence_checksum_errors\":0",
    "\"mutable_fs_mounts\":2",
    "\"mutable_fs_files\":8",
    "\"mutable_fs_directories\":11",
    "\"mutable_fs_writes\":26",
    "\"mutable_fs_reads\":8",
    "\"mutable_fs_deletes\":1",
    "\"mutable_fs_commits\":4",
    "\"mutable_fs_rollbacks\":3",
    "\"mutable_fs_replays\":1",
    "\"mutable_fs_journal_writes\":1",
    "\"mutable_fs_multi_sector_files\":1",
    "\"mutable_fs_state_records\":16",
    "\"mutable_fs_renames\":1",
    "\"mutable_fs_lists\":1",
    "\"mutable_fs_stats\":4",
    "\"mutable_fs_opens\":5",
    "\"mutable_fs_closes\":5",
    "\"mutable_fs_rejects\":8",
    "\"mutable_fs_checksum_errors\":0",
    "\"update_transactions\":2",
    "\"update_staged\":2",
    "\"update_committed\":1",
    "\"update_failures\":1",
    "\"update_recoveries\":1",
    "\"update_rollbacks\":1",
    "\"update_boot_fallbacks\":1",
    "\"update_records_persisted\":8",
    "\"update_rollback_points\":2",
    "\"update_rejects\":2",
    "\"migration_total\":0",
    "\"context_switch_total\":0",
    "\"source_index_updates\":1",
    "\"security_denied_ops\":22",
    "\"security_capability_denials\":5",
    "\"security_fs_denials\":1",
    "\"security_workspace_denials\":4",
    "\"security_sandbox_denials\":3",
    "\"security_rollback_denials\":1",
    "\"security_update_policy_rejects\":3",
    "\"security_credential_rejects\":3",
    "\"security_signature_accepts\":3",
    "\"security_signature_rejects\":3",
    "\"security_admin_denials\":2",
    "\"security_update_authorizations\":3",
    "\"security_update_replay_rejects\":1",
    "\"security_key_accepts\":3",
    "\"security_key_rejects\":1",
    "\"security_sandbox_escape_rejects\":2",
    "\"network_udp_tx\":3",
    "\"network_udp_rx\":3",
    "\"network_udp_malformed\":1",
    "\"network_udp_dropped\":1",
    "\"network_udp_flows\":1",
    "\"network_udp_flow_hits\":1",
    "\"network_udp_expired\":1",
    "\"network_tcp_connections\":1",
    "\"network_tcp_timeouts\":1",
    "\"network_tcp_retransmits\":1",
    "\"network_tcp_established\":1",
    "\"network_tcp_closed\":1",
    "\"network_rx_packets\":6",
    "\"network_tx_packets\":6",
    "\"network_packet_drops\":2",
    "\"network_packet_lifecycle\":18",
    "\"network_queue_rx_enqueues\":6",
    "\"network_queue_tx_enqueues\":6",
    "\"network_queue_completions\":6",
    "\"network_queue_backpressure_drops\":0",
    "\"network_flow_core_mismatches\":0",
    "\"network_udp_p999\"",
    "\"network_tcp_p999\"",
    "\"ai_cell_transitions\":14",
    "\"ai_cell_descriptor_accepts\":5",
    "\"ai_cell_descriptor_rejects\":4",
    "\"ai_cell_resource_admissions\":2",
    "\"ai_cell_resource_rejects\":10",
    "\"ai_cell_arena_pages_reserved\":0",
    "\"ai_cell_arena_bytes_reserved\":0",
    "\"ai_cell_arena_pages_peak\":160",
    "\"ai_cell_arena_bytes_peak\":655360",
    "\"ai_cell_queue_binds\":3",
    "\"ai_cell_queue_releases\":3",
    "\"ai_cell_workspace_binds\":2",
    "\"ai_cell_workspace_releases\":2",
    "\"ai_cell_conflicts\":3",
    "\"cpu_ai_model_loads\":4",
    "\"cpu_ai_model_load_failures\":3",
    "\"cpu_ai_tokenizer_calls\":4",
    "\"cpu_ai_runtime_calls\":4",
    "\"cpu_ai_kv_writes\":16",
    "\"cpu_ai_shared_weight_binds\":4",
    "\"cpu_ai_gpu_rejects\":1",
    "\"cpu_ai_model_file_loads\":1",
    "\"cpu_ai_model_file_rejects\":3",
    "\"cpu_ai_model_bytes_loaded\"",
    "\"cpu_ai_manifest_validations\":9",
    "\"cpu_ai_tokenizer_binds\":4",
    "\"cpu_ai_kernel_dispatches\":4",
    "\"cpu_ai_admission_rejects\":5",
    "\"cpu_ai_checksum_failures\":1",
    "user: loaded /init ELF",
    "user: process pid=1 name=/init state=running",
    "user: rejected syscall=99",
    "user: rejected syscall=1",
    "/init: bad syscall tests passed",
    "/init: hello from ELF",
    "service-manager: configured /init restart=never log=serial max_restarts=0",
    "service-manager: log /init manager-ready records=1",
    "/init: service manager policy ready",
    "service-manager: restart denied /init policy=never attempts=1",
    "/init: restart denied by policy",
    "service: /init state=running",
    "/init: service setup complete",
    "rejected=3",
    "user: /init exited status=0",
    "user: process pid=1 name=/init state=exited",
    "user: kernel resumed after EL0 pid=1 state=exited exit_code=0",
    "kernel: /init returned to kernel exit_code=0",
    "user: reclaimed address space pid=1",
    "user: loaded /bin/service-manager ELF",
    "user: process pid=2 name=/bin/service-manager state=running",
    "/service-manager: hello from ELF",
    "user: service descriptor read path=/etc/services/source-index.svc",
    "/service-manager: descriptor loaded",
    "user: rejected syscall=9",
    "user: rejected syscall=10",
    "/service-manager: missing capability tests passed",
    "service-manager: defined child /svc/source-index parent=/init restart=never",
    "service-supervisor: tree parent=/init child=/svc/source-index children=1 edges=1",
    "service: /svc/source-index state=running",
    "service: /svc/source-index mutable-state persisted state=running",
    "osctl: /svc/source-index state=running",
    "service-manager: restart denied /svc/source-index policy=never",
    "/service-manager: child service supervised",
    "service-manager: configured /svc/source-index restart=always log=serial max_restarts=2",
    "service-manager: log /svc/source-index crash-test records=1",
    "service-supervisor: observed crash /svc/source-index code=7 parent=/init",
    "service: /svc/source-index state=failed exit_code=7",
    "service-supervisor: cleanup /svc/source-index reason=crash cleanups=1",
    "service-supervisor: restarting child /svc/source-index parent=/init attempt=2",
    "/service-manager: child crash supervised",
    "admin: policy ssh_only=1 password_login=0 admin_cap_required=1 remote_safe_allowlist=1 exports=1",
    "admin: status service=/svc/source-index state=running",
    "mutable-fs: write path=/state/services/admin.state",
    "admin: logs service=/svc/source-index records=1",
    "admin: remote-safe command=status accepted accepts=1",
    "admin: remote-safe command=shell rejected rejects=1",
    "/service-manager: admin status exported",
    "/service-manager: remote-safe checks passed",
    "osctl: status qemu=running",
    "osctl: ps slots=8",
    "osctl: services transitions=",
    "osctl: cells transitions=",
    "osctl: fs files=",
    "osctl: net udp_tx=",
    "osctl: telemetry cpu_ai_loads=",
    "osctl: update transactions=",
    "osctl: rollback persistence=",
    "/service-manager: osctl command surface passed",
    "/service-manager: mutable fs syscalls passed",
    "/service-manager: control plane complete",
    "user: /bin/service-manager exited status=0",
    "kernel: /bin/service-manager returned to kernel exit_code=0",
    "scheduler: process pid=3 parent=2 runnable name=/bin/osai-worker",
    "scheduler: dispatch pid=3 parent=2 name=/bin/osai-worker",
    "kernel: /bin/osai-worker pid=3 returned to kernel exit_code=0",
    "scheduler: process pid=4 parent=2 runnable name=/bin/osai-worker",
    "scheduler: dispatch pid=4 parent=2 name=/bin/osai-worker",
    "kernel: /bin/osai-worker pid=4 returned to kernel exit_code=0",
    "scheduler: process pid=5 parent=2 runnable name=/bin/osai-worker",
    "scheduler: dispatch pid=5 parent=2 name=/bin/osai-worker",
    "kernel: /bin/osai-worker pid=5 returned to kernel exit_code=0",
    "/worker: scheduled child process ran",
    "\"service_tree_edges\":1",
    "\"service_restarts\":1",
    "\"service_crashes\":1",
    "\"service_cleanups\":6",
    "\"service_log_records\":2",
    "\"admin_policy_exports\":1",
    "\"admin_status_exports\":2",
    "\"admin_log_reads\":1",
    "\"admin_remote_safe_accepts\":1",
    "\"admin_remote_safe_rejects\":1",
    "\"admin_command_denials\":0",
    "\"user_process_transitions\":18",
    "\"user_process_loaded\":5",
    "\"user_process_runnable\":3",
    "\"user_process_running\":5",
    "\"user_process_waiting\":0",
    "\"user_process_exited\":5",
    "\"user_process_failed\":0",
    "\"user_process_reclaims\":5",
    "\"user_process_scheduled\":5",
    "\"user_process_active\":0",
    "\"service_child_descriptors\":1",
    "\"control_plane_syscalls\":34",
    "\"control_plane_denials\"",
    "\"service_descriptor_reads\":1",
]


def telemetry_line_complete(text):
    marker = "telemetry: {"
    start = text.rfind(marker)
    return start >= 0 and "\n" in text[start:]


def main() -> int:
    env = os.environ.copy()
    env["OSAI_QEMU_HOSTFWD_PORT"] = "none"
    proc = subprocess.Popen(
        ["make", "qemu-aarch64"],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
        env=env,
        start_new_session=True,
    )
    seen = []
    deadline = time.time() + int(os.environ.get("OSAI_QEMU_SMOKE_TIMEOUT", "60"))
    try:
        fd = proc.stdout.fileno()
        while time.time() < deadline:
            ready, _, _ = select.select([fd], [], [], 0.2)
            if ready:
                chunk = os.read(fd, 4096).decode("utf-8", errors="replace")
                if not chunk:
                    break
                sys.stdout.write(chunk)
                sys.stdout.flush()
                seen.append(chunk)
                text = "".join(seen)
                if (all(target in text for target in TARGETS) and
                        telemetry_line_complete(text)):
                    print("\nQEMU smoke boot reached all full userspace/resource markers")
                    return 0
            elif proc.poll() is not None:
                break
    finally:
        if proc.poll() is None:
            os.killpg(proc.pid, signal.SIGTERM)
            try:
                proc.wait(timeout=3)
            except subprocess.TimeoutExpired:
                os.killpg(proc.pid, signal.SIGKILL)
                proc.wait(timeout=3)

    text = "".join(seen)
    missing = [target for target in TARGETS if target not in text]
    print("\nmissing targets:", missing)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
